# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c01ce8074cf796e93969ca9af9e181d9e626b3512d2a5bc1f5c477370eef3e2dbd55321c3349a736f65a4a4b4176669cdc7385353c931acd25e3426c3fa20fcc

test:
  secret_key_base: c6aff5f2f5dd65a7d28ada56f1b238b0fa42cf80e5f282a1c82694170c2d00964d2d17ba2f0eb9fecf839bbc79f81a2429513038a5bb17e88bfcef791359b89f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
